import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowRight, BarChart3, Bell, BookOpen, BriefcaseBusiness, Check, ChevronDown, ChevronRight, CircleHelp, Clock3, Headphones, Inbox, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Search, Settings, Sparkles, Users } from 'lucide-react';
import { agents, initialConversations, initialCustomers, knowledgeExamples } from './data';
import { Avatar, Heading, initialsColor } from './components/Shared';
import DashboardPage from './pages/DashboardPage';
import InboxPage from './pages/InboxPage';
import CustomersPage from './pages/CustomersPage';
import KnowledgePage from './pages/KnowledgePage';
import TeamPage from './pages/TeamPage';
import InsightsPage from './pages/InsightsPage';
import SettingsPage from './pages/SettingsPage';
import { listKnowledgeDocuments, queryKnowledge, uploadKnowledgeDocument } from './services/knowledgeApi';
import { loadWorkspace, saveWorkspace } from './services/localStore';
import NewConversationModal from './components/NewConversationModal';
import { suggestReply, transformDraft } from './services/aiService';

const sections = [{ id: 'dashboard', label: 'Visão geral', icon: LayoutDashboard }, { id: 'inbox', label: 'Caixa de entrada', icon: Inbox }, { id: 'customers', label: 'Clientes', icon: Users }, { id: 'knowledge', label: 'Base de conhecimento', icon: BookOpen }, { id: 'team', label: 'Equipe', icon: BriefcaseBusiness }, { id: 'insights', label: 'Métricas', icon: BarChart3 }];
const agentById = (id) => agents.find((item) => item.id === id) || agents[0];
const timeNow = () => new Intl.DateTimeFormat('pt-BR', { hour: '2-digit', minute: '2-digit' }).format(new Date());

export default function ServixApp() {
  const [page, setPage] = useState('dashboard'), [drawer, setDrawer] = useState(false);
  const [workspace, setWorkspace] = useState(() => { const seededArticles = knowledgeExamples.map((item, index) => ({ ...item, id: `article-${index + 1}`, category: item.category === 'Produtos e preços' ? 'Produtos' : item.category, content: item.detail, published: true })); const saved = loadWorkspace({ conversations: initialConversations, customers: initialCustomers, team: agents, articles: seededArticles, activity: [], settings: { company: 'Norte Studio', profileName: 'Camila Mendes', profileEmail: 'camila@nortestudio.com.br', hours: 'Segunda a sexta, 9h às 18h', autoReply: '', notifications: true, aiEnabled: true, compact: false } }); return { ...saved, articles: saved.articles?.length ? saved.articles.map((item) => ({ ...item, category: item.category === 'Produtos e preços' ? 'Produtos' : item.category })) : seededArticles, settings: { profileName: 'Camila Mendes', profileEmail: 'camila@nortestudio.com.br', compact: false, ...saved.settings }, team: saved.team.map((person) => ({ ...person, role: person.role === 'Gestora' ? 'Gestor' : person.role === 'Atendimento' ? 'Atendente' : person.role })) }; });
  const { conversations: items, customers, team, articles, activity, settings } = workspace;
  const setItems = (update) => setWorkspace((prev) => ({ ...prev, conversations: typeof update === 'function' ? update(prev.conversations) : update }));
  const setCustomers = (update) => setWorkspace((prev) => ({ ...prev, customers: typeof update === 'function' ? update(prev.customers) : update }));
  const setTeam = (update) => setWorkspace((prev) => ({ ...prev, team: typeof update === 'function' ? update(prev.team) : update }));
  const setArticles = (update) => setWorkspace((prev) => ({ ...prev, articles: typeof update === 'function' ? update(prev.articles) : update }));
  const setSettings = (update) => setWorkspace((prev) => ({ ...prev, settings: typeof update === 'function' ? update(prev.settings) : update }));
  const [selectedId, setSelectedId] = useState('cv1'), [mobileList, setMobileList] = useState(true), [filter, setFilter] = useState('Todas'), [query, setQuery] = useState(''), [personFilter, setPersonFilter] = useState('Todos'), [text, setText] = useState(''), [toast, setToast] = useState(''), [ai, setAi] = useState({ busy: false, result: '', draft: false }), [documents, setDocuments] = useState([]), [knowledgeStatus, setKnowledgeStatus] = useState('idle');
  const [newConversation, setNewConversation] = useState(false);
  useEffect(() => { if (!saveWorkspace(workspace)) flash('Armazenamento local indisponível; alterações duram até fechar esta sessão.'); }, [workspace]);
  const current = items.find((item) => item.id === selectedId) || items[0], customer = customers.find((item) => item.id === current?.customerId) || customers[0];
  const messageList = useMemo(() => items.filter((item) => !item.archived && (filter === 'Todas' || item.status === filter) && (personFilter === 'Todos' || item.owner === personFilter) && `${item.subject} ${customers.find((person) => person.id === item.customerId)?.name}`.toLowerCase().includes(query.toLowerCase())), [items, filter, personFilter, query, customers]);
  const flash = (value) => { setToast(value); window.clearTimeout(window.servixToastTimer); window.servixToastTimer = window.setTimeout(() => setToast(''), 2800); };
  const navigate = (id) => { setPage(id); setDrawer(false); if (id === 'inbox') setMobileList(true); setAi({ busy: false, result: '', draft: false }); if (id === 'knowledge' && knowledgeStatus === 'idle') void loadDocs(); };
  const loadDocs = async () => { setKnowledgeStatus('loading'); try { setDocuments(await listKnowledgeDocuments()); setKnowledgeStatus('connected'); } catch { setKnowledgeStatus('offline'); } };
  const uploadDoc = async (file) => { if (!file) return; if (!/\.(txt|md)$/i.test(file.name)) { flash('Envie um arquivo .txt ou .md.'); return; } try { const doc = await uploadKnowledgeDocument(file); setDocuments((prev) => [doc, ...prev]); flash('Material adicionado à base.'); } catch (error) { flash(error.message || 'Conecte a API para enviar materiais.'); } };
  const log = (label) => setWorkspace((prev) => ({ ...prev, activity: [{ id: Date.now(), label, time: timeNow() }, ...prev.activity].slice(0, 30) }));
  const send = (event, attachment) => { event?.preventDefault(); if ((!text.trim() && !attachment) || !current) return; const reply = { id: Date.now(), from: 'agent', text: text.trim() || 'Arquivo anexado', ...(attachment ? { attachment } : {}), time: timeNow() }; setItems((prev) => prev.map((item) => item.id === selectedId ? { ...item, messages: [...item.messages, reply], unread: false, status: item.status === 'Resolvida' ? 'Aberta' : item.status, time: reply.time } : item)); setCustomers((prev) => prev.map((item) => item.id === customer.id ? { ...item, lastContact: `Hoje, ${reply.time}` } : item)); log(`Resposta enviada para ${customer.name}`); setText(''); flash('Resposta adicionada à conversa.'); };
  const createCustomer = (values) => { const id = `c${Date.now()}`; const person = { ...values, id, initials: values.name.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase(), tags: values.tags.split(',').map((tag) => tag.trim()).filter(Boolean), status: 'Ativo', createdAt: new Date().toISOString(), lastContact: 'Sem contato' }; setCustomers((prev) => [person, ...prev]); log(`${person.name} foi adicionado(a) como cliente`); flash('Cliente criado.'); return person; };
  const createConversation = (customerId, subject, firstMessage, owner, createdCustomer) => { const person = createdCustomer || customers.find((entry) => entry.id === customerId); if (!person || !subject.trim() || !firstMessage.trim()) return; const id = `cv${Date.now()}`; const created = { id, customerId, subject: subject.trim(), channel: 'Chat', status: 'Aberta', priority: 'Normal', unread: false, owner, time: timeNow(), createdAt: new Date().toISOString(), messages: [{ id: Date.now(), from: 'customer', text: firstMessage.trim(), time: timeNow() }] }; setItems((prev) => [created, ...prev]); setSelectedId(id); log(`Nova conversa iniciada com ${person.name}`); navigate('inbox'); setMobileList(false); flash('Conversa criada.'); };
  const assist = async (action) => { if (!settings.aiEnabled) { setAi({ busy: false, result: 'O assistente Servix AI está desativado nas configurações.', draft: false }); return; } if (!action) { setAi({ busy: false, result: '', draft: false }); return; } if (action === 'Resumo' || action === 'Intenção') { const last = [...current.messages].reverse().find((item) => item.from === 'customer'); const intent = /orçamento|proposta/i.test(current.subject) ? 'esclarecer a proposta' : /senha|acesso/i.test(current.subject) ? 'recuperar acesso' : /renovação/i.test(current.subject) ? 'avaliar a renovação' : 'obter ajuda com o atendimento'; setAi({ busy: false, draft: false, result: action === 'Resumo' ? `Resumo demonstrativo: ${customer.name} entrou em contato sobre ${current.subject.toLowerCase()}. ${last?.text || ''}` : `Intenção provável (classificação demonstrativa): ${intent}.` }); return; } if (['Tornar mais amigável','Tornar mais profissional','Melhorar resposta'].includes(action)) { setAi({ busy: false, draft: true, result: transformDraft(action, current, customer) }); return; } setAi({ busy: true, draft: false, result: '' }); try { if (import.meta.env.VITE_AI_API_URL) { const assisted = await suggestReply({ conversation: current, customer, articles }); setAi({ busy: false, draft: true, result: assisted.answer }); return; } const result = await queryKnowledge(`Sugira uma resposta cordial e concisa ao cliente com base apenas na conversa e na base da empresa. Não invente prazos, preços nem políticas.\n${current.messages.map((m) => `${m.from === 'agent' ? 'Equipe' : customer.name}: ${m.text}`).join('\n')}`); if (result.mode === 'ai' || result.mode === 'provider') setAi({ busy: false, draft: true, result: result.answer }); else { const demo = await suggestReply({ conversation: current, customer, articles }); setAi({ busy: false, draft: true, result: `${demo.answer} (sugestão demonstrativa)` }); } } catch { try { const demo = await suggestReply({ conversation: current, customer, articles }); setAi({ busy: false, draft: true, result: `${demo.answer} (sugestão demonstrativa)` }); } catch { setAi({ busy: false, draft: false, result: 'O gateway de IA está indisponível. Confira a conversa e a base antes de responder.' }); } } };
  const changeStatus = () => { const status = current.status === 'Resolvida' ? 'Aberta' : 'Resolvida'; setItems((prev) => prev.map((item) => item.id === current.id ? { ...item, status } : item)); log(`Conversa ${current.subject}: ${status.toLowerCase()}`); flash(`Atendimento ${status.toLowerCase()}.`); };
  const changeConversation = (id) => { setSelectedId(id); setMobileList(false); setAi({ busy: false, result: '', draft: false }); setItems((prev) => prev.map((item) => item.id === id ? { ...item, unread: false } : item)); };
  return <div className={`servix-app${settings.compact ? ' compact-mode' : ''}`}>{drawer && <button className="mobile-scrim" aria-label="Fechar menu" onClick={() => setDrawer(false)}/>}<aside className={`sidebar${drawer ? ' sidebar-open' : ''}`}><button className="wordmark" aria-label="Servix — Serviços. Conexões. Confiança." onClick={() => navigate('dashboard')}><span className="wordmark-image" role="img" aria-label="Servix"/></button><button className="workspace-selector" onClick={() => navigate('settings')}><span className="workspace-icon">N</span><span className="workspace-copy"><b>{settings.company}</b><small>Plano Equipe</small></span><ChevronDown size={15}/></button><div className="sidebar-label">ESPAÇO DE TRABALHO</div><nav className="sidebar-nav">{sections.map(({ id, label, icon: Icon }) => <button key={id} className={`side-link${page === id ? ' selected' : ''}`} onClick={() => navigate(id)}><Icon size={17}/><span>{label}</span>{id === 'inbox' && <span className="side-badge">{items.filter((item) => item.unread && !item.archived).length}</span>}</button>)}</nav><div className="sidebar-section-label">CONFIGURAÇÃO</div><button className={`side-link${page === 'settings' ? ' selected' : ''}`} onClick={() => navigate('settings')}><Settings size={17}/><span>Configurações</span></button><div className="sidebar-fill"/><div className="plan-note"><span className="plan-spark"><Sparkles size={14}/></span><strong>Seu time, em sintonia.</strong><p>Veja como o Servix ajuda sua equipe a cuidar de cada conversa.</p><button onClick={() => navigate('insights')}>Ver métricas <ArrowRight size={13}/></button></div><button className="account-row" onClick={() => navigate('settings')}><Avatar person={{ ...agents[0], initials: settings.profileName.split(/\s+/).slice(0,2).map((v)=>v[0]).join('').toUpperCase() }} size="small"/><span className="account-copy"><b>{settings.profileName}</b><small>{team.find((person) => person.id === 'camila')?.role || 'Atendente'}</small></span><MoreHorizontal size={18}/></button></aside>
    <main className="main-frame"><header className="topbar"><div className="topbar-left"><button className="mobile-menu" aria-label="Abrir navegação" onClick={() => setDrawer(true)}><Menu size={19}/></button><div className="breadcrumbs"><span>{settings.company}</span><ChevronRight size={13}/><strong>{sections.find((item) => item.id === page)?.label || 'Configurações'}</strong></div></div><div className="topbar-right"><button className="command-search" onClick={() => { navigate('inbox'); document.querySelector('.conversation-search input')?.focus(); }}><Search size={15}/><span>Buscar</span><kbd>⌘ K</kbd></button><span className="topbar-divider"/><button className="help-action" title="Ajuda" onClick={() => flash('Fale com a pessoa administradora deste espaço para obter ajuda.')}><CircleHelp size={17}/></button><button className="notification-button" title="Notificações" onClick={() => { navigate('inbox'); flash(`${items.filter((item) => item.unread && !item.archived).length} conversas não lidas.`); }}><Bell size={17}/><i/></button><span className="topbar-divider"/><Avatar person={agents[0]} size="small"/></div></header><div className="page-scroll">
      {page === 'dashboard' && <DashboardPage conversations={items} customers={customers} team={team} activity={activity} changePage={navigate} setSelectedConversation={changeConversation}/>}
      {page === 'inbox' && <InboxPage conversations={items} customers={customers} team={team} current={current} customer={customer} matching={messageList} selectedId={selectedId} setSelectedId={changeConversation} mobileList={mobileList} setMobileList={setMobileList} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} agentFilter={personFilter} setAgentFilter={setPersonFilter} message={text} setMessage={setText} sendMessage={send} aiResult={ai.result} aiIsDraft={ai.draft} aiBusy={ai.busy} runAssist={assist} updateStatus={changeStatus} flash={flash} showCustomerDetails={true} setShowCustomerDetails={() => {}} enterKnowledge={() => navigate('knowledge')} openNewConversation={() => setNewConversation(true)} updateConversation={(id, change) => { const target = items.find((item) => item.id === id); setItems((prev) => prev.map((item) => item.id === id ? { ...item, ...change } : item)); if (change.owner && target) setCustomers((prev) => prev.map((person) => person.id === target.customerId ? { ...person, owner: change.owner } : person)); }}/>}
      {page === 'customers' && <CustomersPage customers={customers} conversations={items} team={team} search={query} setSearch={setQuery} selected={customers.find((item) => item.id === selectedId) || customers[0]} setSelected={(id) => setSelectedId(id)} changePage={navigate} setSelectedConversation={changeConversation} updateCustomers={setCustomers} updateConversations={setItems} createCustomer={createCustomer} flash={flash}/>}
      {page === 'knowledge' && <KnowledgePage articles={articles} updateArticles={setArticles} documents={documents} uploadState={knowledgeStatus} apiError={knowledgeStatus === 'offline' ? 'Conecte o backend FastAPI em localhost:8000 para consultar e armazenar documentos.' : ''} uploadDocument={uploadDoc} askKnowledge={async (question) => { setAi({ busy: true, draft: false, result: '' }); try { const result = await queryKnowledge(question); setAi({ busy: false, draft: false, result: result.mode === 'ai' ? result.answer : 'O assistente está em modo de demonstração. A consulta foi recebida; conecte um provedor de IA para gerar uma resposta baseada nos documentos.' }); } catch { setAi({ busy: false, draft: false, result: 'A API de conhecimento não está disponível. Os artigos locais continuam acessíveis à equipe.' }); } }} aiResult={ai.result} aiBusy={ai.busy} onRefresh={loadDocs}/>}
      {page === 'team' && <TeamPage team={team} updateTeam={setTeam} log={log} flash={flash}/>} {page === 'insights' && <InsightsPage conversations={items} customers={customers} team={team}/>} {page === 'settings' && <SettingsPage settings={settings} updateSettings={setSettings} navigate={navigate} flash={flash}/>}
    </div><footer className="global-footer"><span>© 2026 Servix</span><span><i/> Dados salvos neste dispositivo</span><button onClick={() => flash('Fale com o administrador da organização para receber suporte.')}><Headphones size={13}/> Fale com o suporte</button></footer></main>{newConversation && <NewConversationModal customers={customers} team={team} onClose={() => setNewConversation(false)} onCreate={createConversation} onNewCustomer={createCustomer}/>} {toast && <div className="servix-toast" role="status"><Check size={16}/>{toast}</div>}</div>;
}
