import { useState } from 'react';
import { X, UserRoundPlus } from 'lucide-react';
import { agents } from '../data';

export default function NewConversationModal({ customers, team = agents, onClose, onCreate, onNewCustomer }) {
  const [customerId, setCustomerId] = useState(customers[0]?.id || '');
  const [creating, setCreating] = useState(false);
  const [name, setName] = useState(''), [email, setEmail] = useState(''), [phone, setPhone] = useState('');
  const [subject, setSubject] = useState(''), [message, setMessage] = useState(''), [owner, setOwner] = useState(team[0]?.id || agents[0].id);
  const submit = (event) => { event.preventDefault(); let id = customerId, created; if (creating) { if (!name.trim()) return; created = onNewCustomer({ name, email, phone, company: '', owner, note: '', tags: '' }); id = created.id; } onCreate(id, subject, message, owner, created); onClose(); };
  return <div className="servix-modal-scrim" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><form className="servix-modal" onSubmit={submit} aria-labelledby="new-conversation-title"><header><div><span className="panel-kicker">ATENDIMENTO</span><h2 id="new-conversation-title">Nova conversa</h2></div><button type="button" className="icon-button" aria-label="Fechar" onClick={onClose}><X size={17}/></button></header><div className="servix-modal-body"><div className="modal-choice"><button type="button" className={!creating ? 'active' : ''} onClick={() => setCreating(false)}>Cliente existente</button><button type="button" className={creating ? 'active' : ''} onClick={() => setCreating(true)}><UserRoundPlus size={14}/> Novo cliente</button></div>{creating ? <><label>Nome<input required value={name} onChange={(e) => setName(e.target.value)} autoFocus/></label><label>E-mail<input type="email" value={email} onChange={(e) => setEmail(e.target.value)}/></label><label>Telefone<input value={phone} onChange={(e) => setPhone(e.target.value)}/></label></> : <label>Cliente<select required value={customerId} onChange={(e) => setCustomerId(e.target.value)}>{customers.map((person) => <option key={person.id} value={person.id}>{person.name} · {person.company}</option>)}</select></label>}<label>Assunto<input required value={subject} onChange={(e) => setSubject(e.target.value)} placeholder="Ex.: Dúvida sobre contratação"/></label><label>Mensagem inicial<textarea required rows={3} value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Registre a primeira mensagem recebida"/></label><label>Responsável<select value={owner} onChange={(e) => setOwner(e.target.value)}>{team.map((agent) => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select></label></div><footer><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" type="submit">Criar conversa</button></footer></form></div>;
}
