import { useMemo, useState } from 'react';
import { Activity, CheckCheck, Clock3, MessageCircle, Users } from 'lucide-react';
import { Heading } from '../components/Shared';
export default function InsightsPage({ conversations, customers = [], team = [] }) {
  const [range, setRange] = useState(7);
  const cutoff = Date.now() - range * 86400000;
  const data = useMemo(() => conversations.filter((item) => !item.createdAt || new Date(item.createdAt).getTime() >= cutoff), [conversations, cutoff]);
  const resolved = data.filter((item) => item.status === 'Resolvida').length, waiting = data.filter((item) => item.status === 'Pendente').length, open = data.filter((item) => item.status === 'Aberta').length;
  const responsePairs = data.reduce((n, item) => n + item.messages.filter((m) => m.from === 'agent').length, 0);
  const response = responsePairs ? Math.max(1, Math.round(data.reduce((n, item) => n + item.messages.length, 0) * 2 / responsePairs)) : 0;
  const byAgent = team.map((person) => ({ ...person, count: data.filter((item) => item.owner === person.id).length, resolved: data.filter((item) => item.owner === person.id && item.status === 'Resolvida').length })).sort((a,b) => b.count-a.count);
  const newCustomers = customers.filter((person) => person.createdAt && new Date(person.createdAt).getTime() >= cutoff).length;
  const subjects = Object.entries(data.reduce((acc, item) => { acc[item.subject] = (acc[item.subject] || 0) + 1; return acc; }, {})).sort((a,b) => b[1]-a[1]).slice(0,5);
  return <div className="content"><Heading eyebrow="VISÃO DA OPERAÇÃO" title="Métricas" description="Indicadores calculados a partir das conversas e clientes deste espaço." action={<select aria-label="Período das métricas" value={range} onChange={(e) => setRange(Number(e.target.value))}><option value={1}>Hoje</option><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option></select>}/><section className="metrics-row"><div className="metric-card"><MessageCircle size={17}/><span className="metric-label">Conversas no período</span><strong>{data.length}</strong></div><div className="metric-card"><Clock3 size={17}/><span className="metric-label">Primeira resposta estimada</span><strong>{response} min</strong></div><div className="metric-card"><CheckCheck size={17}/><span className="metric-label">Resolvidas</span><strong>{data.length ? Math.round(resolved/data.length*100) : 0}%</strong></div><div className="metric-card"><Users size={17}/><span className="metric-label">Novos clientes registrados</span><strong>{newCustomers}</strong></div></section><div className="insight-grid"><article className="panel"><div className="panel-heading"><h2>Conversas por status</h2></div>{[['Abertas',open],['Aguardando',waiting],['Resolvidas',resolved]].map(([label,value])=><div className="response-foot" key={label}><span>{label}</span><b>{value}</b></div>)}</article><article className="panel"><div className="panel-heading"><h2>Desempenho por atendente</h2></div>{byAgent.map((person)=> <div className="response-foot" key={person.id}><span>{person.name} · {person.resolved} resolvidas</span><b>{person.count} conversas</b></div>)}{!byAgent.length && <p className="response-caption">Adicione pessoas à equipe para acompanhar a distribuição.</p>}</article><article className="panel"><div className="panel-heading"><h2>Principais assuntos</h2></div>{subjects.map(([title,count])=><div className="response-foot" key={title}><span>{title}</span><b>{count}</b></div>)}{!subjects.length && <p className="response-caption">Ainda não há conversas no período escolhido.</p>}</article><article className="panel"><div className="panel-heading"><h2>Como ler estes números</h2></div><p className="response-caption">O volume, a resolução e a distribuição vêm dos registros locais. A primeira resposta é uma estimativa baseada no número de mensagens; tempos reais exigem eventos com data/hora do backend.</p></article></div><p className="metrics-footnote"><Activity size={14}/> Dados locais de demonstração. Período selecionado: {range === 1 ? 'Hoje' : `${range} dias`}.</p></div>;
}
